### PR TITLE
Update to gs 9.54.0

### PR DESCRIPTION
**Pull request by FelixMoelder**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by FelixMoelder** [comment]
@conda-forge-admin, please rerender

**Comment by FelixMoelder** [comment]
It looks like there is a [bug](http://git.ghostscript.com/?p=ghostpdl.git;a=commit;h=d0440b33c132692654dab2fc74cc8024e39f95a5) that prevents building on osx64.

**Comment by tdegeus** [comment]
Thanks @FelixMoelder . If the fix for the bug is merged in GhostScript, personally I would be happy to apply it here using a (number of) patch(es) here.

**Comment by FelixMoelder** [comment]
> Thanks @FelixMoelder . If the fix for the bug is merged in GhostScript, personally I would be happy to apply it here using a (number of) patch(es) here.

I just tried to apply the referenced changes as a patch but building still keeps failing.

Looking at the [release notes](https://www.ghostscript.com/doc/9.54.0/News.htm) states the following:

> Mainly due to time constraints, we only support including Tesseract from source included in our release packages, and not linking to Tesseract/Leptonica shared libraries. Whether we add this capability will be largely dependent on community demand for the feature.

I am not that much into C to tell if this might be related to the issue.
Still, one way to get this building on osx is to disable Tesseract by adding `--without-tesseract`

**Comment by tdegeus** [comment]
> I am not that much into C to tell if this might be related to the issue.
> Still, one way to get this building on osx is to disable Tesseract by adding `--without-tesseract`

It is a bit surprising / disappointing that the patch did not solve things. BTW, I assume that you tried locally on your mac, because I could not find a trace here.

I'm not sure what would the limitation of `--without-tesseract` ?

**Comment by FelixMoelder** [comment]
> > I am not that much into C to tell if this might be related to the issue.
> > Still, one way to get this building on osx is to disable Tesseract by adding `--without-tesseract`
> 
> It is a bit surprising / disappointing that the patch did not solve things. BTW, I assume that you tried locally on your mac, because I could not find a trace here.
> 
> I'm not sure what would the limitation of `--without-tesseract` ?

You are right, I tried it locally as I did not want to mess around with the PR trying several stuff.
Finally, I got it working by just adding tesseract as dependency for osx.
That's a bit confusing to me as the release note states that tesseract must be part of the gs source-package and shared libraries do not work.

**Comment by FelixMoelder** [comment]
> 
> It is a bit surprising / disappointing that the patch did not solve things. BTW, I assume that you tried locally on your mac, because I could not find a trace here.
> 
> I'm not sure what would the limitation of `--without-tesseract` ?

Indeed, I only tested it locally in order to not mess to much with the PR history to get this running.
But I will give it a try here as I only have a `osx-arm64` device for testing.

It looks like tesseract is required to enable OCR features in ghostscript.

**Comment by FelixMoelder** [comment]
I am running out of ideas now.
With the latest patch (see commit) I was able to build ghostscript manually (`./configure`, `make clean`, `make`).
When trying to build via `conda build` locally I receive multiple different errors than initially.
But the CI still keeps failing with the same error...

**Comment by tdegeus** [comment]
@FelixMoelder Honestly I'm quite at loss too. Maybe the other maintainers still have ideas @ocefpaf @leouieda ? Otherwise we need to seek wider help:
- https://gitter.im/conda-forge/conda-forge.github.io
- Registering a bug with ghostscript itself

**Comment by ocefpaf** [comment]
macOS is always a bit painful and I don't have one to test locally.  Maybe we can try a newer sdk?

https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks

**Comment by tdegeus** [comment]
For reference I also found this : https://stackoverflow.com/questions/10116724/clang-os-x-lion-cannot-find-cstdint . The proposed solution is to compile with `-stdlib=libc++`. This, however, seems to be done already...

Like @ocefpaf more recent SDK's might not have this issue : https://github.com/chakra-core/ChakraCore/issues/3519

**Comment by FelixMoelder** [comment]
> macOS is always a bit painful and I don't have one to test locally. Maybe we can try a newer sdk?
> 
> https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks

I will give it a try.
As `conda_build_config.yaml` does not already exist I assume that it is fine to add it manually.

**Comment by tdegeus** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
