### PR TITLE
MNT: rerender

### LINKED ISSUE #24: @conda-forge-admin please rerender
Seems like pcc64le isn't built

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #24.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #24

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
there was a typo for ppc64le. There is a way to specify cross compiling, but the correct flag is azure in this case.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender


Trying to cross compile correctly

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
i'm way too impatient. does ppc cross compilation take longer than aarch cross compilation?

**Comment by tdegeus** [comment]
@hmaarrfk I don't know if ppc would take longer, but 3h40 seems rather long.

**Comment by hmaarrfk** [comment]
It seems like it isn't cross compiling to me.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Pull request merged**
