### PR TITLE
Attempt at fixing conda-forge update detection

### LINKED ISSUE #7: Version outdated?
I got the following notification for my package:

Here is a list of all the pending dependencies (and their versions) for this repo. Please double check all dependencies before merging.

| Name | Upstream Version | Current Version |
|:----:|:----------------:|:---------------:|
|ghostscript|9.27|[Anaconda-Server Badge](https://anaconda.org/conda-forge/ghostscript)|

I guess this means that this package is trailing behind the upstream release. Have you considered updating?

### PR DESCRIPTION
**Pull request by Anthchirp**
Currently the conda-forge bot cannot automatically prepare pull requests
for new versions, as it doesn't understand the 'nopoint' variable.
I'm thinking a Jinja2 native filter _might_ work.
That would then likely fix #7.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
It should not matter b/c the bot should operate on the rendered version. However, I like this way better, merging this. Thanks!

**Comment by Anthchirp** [comment]
the updating bot ended up with a semi-parsed URL:
```
The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!

Please check the URLs in your recipe with version '952' to make sure they exist!

We also found the following errors:

 - could not hash URL template 'https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs922/ghostscript-{{ version }}.tar.gz'
```
922 vs 952

**Comment by ocefpaf** [comment]
Ah. The bot changes so rapidly that I had outdated info. Thanks!

PS: Also kudos to @beckermr for that status page! It saves us a lot of time debugging issues.

**Pull request merged**
