### PR TITLE
Update to 9.53.1

### PR DESCRIPTION
**Pull request by leouieda**
Include @ocefpaf's initial commits from #9 but skip to 9.53.1 to avoid known bugs.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leouieda** [comment]
> The source section contained an unexpected subsection name. sha512 is not a valid subsection name.

😢 thought this would magically work...

**Comment by ocefpaf** [comment]
Things may be working on Windows here b/c Windows somethings has some odd exit codes. I'll try to build this on my Windows machine later today.

**Comment by leouieda** [comment]
Awesome! Thanks @ocefpaf

**Comment by ocefpaf** [comment]
Thank you for reviving this. I forgot about it!

**Pull request merged**
