### PR TITLE
Bump to gs 10.02.0

### PR DESCRIPTION
**Pull request by seisman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by seisman** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@seisman do you want to add yourself as a maintainer here?

**Comment by seisman** [comment]
> @seisman do you want to add yourself as a maintainer here?

Yes, please

**Comment by ocefpaf** [comment]
You should get and invite and be able to merge this PR.

PS: Closes #26

**Comment by seisman** [comment]
Thanks.

**Pull request merged**
