### PR TITLE
Bump to gs 9.56.1

### PR DESCRIPTION
**Pull request by seisman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by seisman** [comment]
@conda-forge-admin, please rerender

**Comment by seisman** [comment]
Although gs 10 is out (https://github.com/conda-forge/ghostscript-feedstock/issues/26), it's still very buggy (see some discussions in https://github.com/GenericMappingTools/gmt/issues/7336). So it makes sense to have v9.56.1, the latest version of gs 9.

**Comment by seisman** [comment]
Ping @leouieda @ocefpaf @tdegeus for reviews.

**Comment by tdegeus** [comment]
Thanks @seisman . Looks good to me. The patch that you removed, is it now part of the upstream package?

**Comment by seisman** [comment]
> The patch that you removed, is it now part of the upstream package?

I have no idea. The upstream source code has changed a lot between gs 9.54 and gs 9.56.1. The patch no longer works.

**Comment by ocefpaf** [comment]
> I have no idea. The upstream source code has changed a lot between gs 9.54 and gs 9.56.1. The patch no longer works.

As far as I can tell one of the changes is upstream and the other on doesn't seem to apply. The patch was introduced in https://github.com/conda-forge/ghostscript-feedstock/pull/6#issuecomment-508591921 to fix the Windows compilation. Windows seems to be working here without it, so let's give this one a try.

**Pull request merged**
