### PR TITLE
V9.52

### PR DESCRIPTION
**Pull request by ocefpaf**
Should also fix the URL version problem.

### CODE REVIEW

**Comment by leouieda** [comment]
Of course the Windows build failed... :disappointed:

**Comment by seisman** [comment]
Glad to see that you're trying to bump Ghostscript to the latest version. However, Ghostscript 9.51 and 9.52 are known to have serious bugs which cannot handle transparency (see https://github.com/GenericMappingTools/gmt/issues/2903 for a related report). The bug was fixed in master but gs 9.53 is planned to be released in September.

To my experience, currently, gs 9.50 is the best one before gs 9.53 is released.

**Comment by ocefpaf** [comment]
Let's wait 9.53 then.

**Comment by seisman** [comment]
FYI, ghostscript 9.53.0 was released recently.

**Comment by leouieda** [comment]
Thanks @seisman! Trying it out in #11

**Pull request closed without merging**
